"""Execution result models for workflow runs."""

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, computed_field


class ExecutionStatus(str, Enum):
    """Status of a node or workflow execution."""

    PENDING = "pending"           # Not yet started
    RUNNING = "running"           # Currently executing
    SUCCESS = "success"           # Completed successfully
    FAILED = "failed"             # Completed with error
    SKIPPED = "skipped"           # Skipped (dependency failed or condition not met)
    CANCELLED = "cancelled"       # Cancelled by user or system
    WAITING_APPROVAL = "waiting_approval"  # Waiting for human approval


class NodeResult(BaseModel):
    """
    Result of executing a single node in the workflow.

    Captures the outcome, outputs, timing, and any errors from
    executing a workflow step.

    Example:
        >>> result = NodeResult(
        ...     node_id="collect-logs-1",
        ...     status=ExecutionStatus.SUCCESS,
        ...     outputs={"log_count": 1523, "error_count": 47}
        ... )
    """

    node_id: str = Field(
        ...,
        description="ID of the node that was executed"
    )

    status: ExecutionStatus = Field(
        default=ExecutionStatus.PENDING,
        description="Current status of this node's execution"
    )

    outputs: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured outputs from the node execution"
    )

    raw_output: Optional[str] = Field(
        default=None,
        description="Raw text/log output from execution"
    )

    error_message: Optional[str] = Field(
        default=None,
        description="Error message if execution failed"
    )

    error_details: Optional[dict[str, Any]] = Field(
        default=None,
        description="Detailed error information (stack trace, error code, etc.)"
    )

    started_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when execution started"
    )

    finished_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when execution finished"
    )

    retry_count: int = Field(
        default=0,
        ge=0,
        description="Number of retry attempts made"
    )

    artifacts: list[str] = Field(
        default_factory=list,
        description="Paths or URLs to artifacts generated by this node"
    )

    @computed_field
    @property
    def duration_seconds(self) -> Optional[float]:
        """Calculate execution duration in seconds."""
        if self.started_at and self.finished_at:
            return (self.finished_at - self.started_at).total_seconds()
        return None

    @computed_field
    @property
    def is_terminal(self) -> bool:
        """Check if this result is in a terminal state."""
        return self.status in {
            ExecutionStatus.SUCCESS,
            ExecutionStatus.FAILED,
            ExecutionStatus.SKIPPED,
            ExecutionStatus.CANCELLED,
        }

    def mark_started(self) -> None:
        """Mark the node as started."""
        self.status = ExecutionStatus.RUNNING
        self.started_at = datetime.utcnow()

    def mark_success(self, outputs: Optional[dict[str, Any]] = None) -> None:
        """Mark the node as successfully completed."""
        self.status = ExecutionStatus.SUCCESS
        self.finished_at = datetime.utcnow()
        if outputs:
            self.outputs.update(outputs)

    def mark_failed(
        self,
        error_message: str,
        error_details: Optional[dict[str, Any]] = None
    ) -> None:
        """Mark the node as failed."""
        self.status = ExecutionStatus.FAILED
        self.finished_at = datetime.utcnow()
        self.error_message = error_message
        self.error_details = error_details

    def mark_skipped(self, reason: str = "Dependency failed") -> None:
        """Mark the node as skipped."""
        self.status = ExecutionStatus.SKIPPED
        self.finished_at = datetime.utcnow()
        self.outputs["skip_reason"] = reason


class ExecutionResult(BaseModel):
    """
    Alias for NodeResult for backward compatibility.

    Use NodeResult for new code.
    """

    node_id: str
    status: ExecutionStatus = ExecutionStatus.PENDING
    outputs: dict[str, Any] = Field(default_factory=dict)
    raw_output: Optional[str] = None
    error_message: Optional[str] = None
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None


class WorkflowRunResult(BaseModel):
    """
    Complete result of executing a workflow.

    Aggregates results from all nodes and provides overall status,
    summary, and timing information.

    Example:
        >>> run_result = WorkflowRunResult(
        ...     workflow_id="wf-20241127-001",
        ...     goal_description="Investigate 5xx errors",
        ...     node_results=[...],
        ... )
    """

    workflow_id: str = Field(
        ...,
        description="ID of the workflow that was executed"
    )

    goal_description: str = Field(
        ...,
        description="The original goal that generated this workflow"
    )

    node_results: list[NodeResult] = Field(
        default_factory=list,
        description="Results for each node in the workflow"
    )

    overall_status: ExecutionStatus = Field(
        default=ExecutionStatus.PENDING,
        description="Overall status of the workflow execution"
    )

    summary: Optional[str] = Field(
        default=None,
        description="Human-readable summary of the execution"
    )

    started_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when workflow execution started"
    )

    finished_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when workflow execution finished"
    )

    artifacts: list[str] = Field(
        default_factory=list,
        description="Paths or URLs to artifacts generated by this run"
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata about the execution"
    )

    @computed_field
    @property
    def duration_seconds(self) -> Optional[float]:
        """Calculate total execution duration in seconds."""
        if self.started_at and self.finished_at:
            return (self.finished_at - self.started_at).total_seconds()
        return None

    @computed_field
    @property
    def success_count(self) -> int:
        """Count of nodes that completed successfully."""
        return sum(1 for r in self.node_results if r.status == ExecutionStatus.SUCCESS)

    @computed_field
    @property
    def failed_count(self) -> int:
        """Count of nodes that failed."""
        return sum(1 for r in self.node_results if r.status == ExecutionStatus.FAILED)

    @computed_field
    @property
    def skipped_count(self) -> int:
        """Count of nodes that were skipped."""
        return sum(1 for r in self.node_results if r.status == ExecutionStatus.SKIPPED)

    def get_node_result(self, node_id: str) -> Optional[NodeResult]:
        """Get the result for a specific node."""
        for result in self.node_results:
            if result.node_id == node_id:
                return result
        return None

    def compute_overall_status(self) -> ExecutionStatus:
        """
        Compute the overall status based on node results.

        Returns:
            The computed overall status.
        """
        if not self.node_results:
            return ExecutionStatus.PENDING

        statuses = [r.status for r in self.node_results]

        # If any node is still running, workflow is running
        if ExecutionStatus.RUNNING in statuses:
            return ExecutionStatus.RUNNING

        # If any node is waiting for approval, workflow is waiting
        if ExecutionStatus.WAITING_APPROVAL in statuses:
            return ExecutionStatus.WAITING_APPROVAL

        # If any node is pending, workflow is still running
        if ExecutionStatus.PENDING in statuses:
            return ExecutionStatus.RUNNING

        # If any node was cancelled, workflow was cancelled
        if ExecutionStatus.CANCELLED in statuses:
            return ExecutionStatus.CANCELLED

        # If any node failed (and wasn't continue_on_failure), workflow failed
        if ExecutionStatus.FAILED in statuses:
            return ExecutionStatus.FAILED

        # All nodes succeeded or were skipped
        return ExecutionStatus.SUCCESS

    def generate_summary(self) -> str:
        """
        Generate a human-readable summary of the execution.

        Returns:
            Summary text describing the execution outcome.
        """
        lines = [
            f"Workflow: {self.workflow_id}",
            f"Goal: {self.goal_description}",
            f"Status: {self.overall_status.value}",
            f"Nodes: {self.success_count} succeeded, {self.failed_count} failed, "
            f"{self.skipped_count} skipped",
        ]

        if self.duration_seconds is not None:
            lines.append(f"Duration: {self.duration_seconds:.2f} seconds")

        # Add details for failed nodes
        failed_nodes = [r for r in self.node_results if r.status == ExecutionStatus.FAILED]
        if failed_nodes:
            lines.append("\nFailed nodes:")
            for node in failed_nodes:
                lines.append(f"  - {node.node_id}: {node.error_message or 'Unknown error'}")

        # Add key outputs from successful nodes
        success_nodes = [r for r in self.node_results if r.status == ExecutionStatus.SUCCESS]
        if success_nodes:
            lines.append("\nKey outputs:")
            for node in success_nodes[:5]:  # Limit to first 5
                if node.outputs:
                    # Show first output key-value
                    key = next(iter(node.outputs.keys()), None)
                    if key:
                        value = node.outputs[key]
                        if isinstance(value, str) and len(value) > 100:
                            value = value[:100] + "..."
                        lines.append(f"  - {node.node_id}: {key}={value}")

        return "\n".join(lines)

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "workflow_id": "wf-example-001",
                    "goal_description": "Investigate 5xx errors",
                    "overall_status": "success",
                    "node_results": [
                        {
                            "node_id": "collect-logs",
                            "status": "success",
                            "outputs": {"log_count": 1523}
                        },
                        {
                            "node_id": "run-rca",
                            "status": "success",
                            "outputs": {"root_cause": "Database connection pool exhausted"}
                        }
                    ],
                    "summary": "Investigation complete. Root cause identified."
                }
            ]
        }
    }
